name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: |
            node_modules
            */*/node_modules

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: |
          npm install
          spago install
          spago -x test.dhall install

      - name: Build source
        run: spago build --no-install --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago -x test.dhall test
